export const GET_AVAILABILITY_WORKSPACES = 'GET_AVAILABILITY_WORKSPACES';
export const POST_OR_PUT_REQUEST_SUCCESS = 'POST_OR_PUT_REQUEST_SUCCESS';
export const POST_OR_PUT_REQUEST_FAILURE = 'POST_OR_PUT_REQUEST_FAILURE';
export const RESET_WORKSPACES_ERRORS = 'RESET_WORKSPACES_ERRORS';

